blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='news'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

jobportal/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.VacancyList.as_view(), name='vacancy'),
    path('<slug:slug>/', views.VacancyDetail.as_view(), name='vacancy_detail'),
    path('search', views.searchjob, name='searchjob'),
]

konsulkarir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('chat/', include('chatchannels.urls')),
    path('news/', include('blog.urls')),
    path('jobportal/', include('jobportal.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobportal/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Company(models.Model):
    user = models.OneToOneField(User, related_name='company', on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=200, unique=True)
    website = models.CharField(max_length=200, blank=True)
    company_size = models.IntegerField()
    industry = models.CharField(max_length=200)
    overview = models.TextField()

    def __str__(self):
        return self.name
    

class Specialization(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name
    

class Vacancy(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='vacancy_posts')
    specialization = models.ForeignKey(Specialization, on_delete=models.DO_NOTHING,related_name='vacancy')
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING,related_name='vacancy')
    salary = models.IntegerField()
    area = models.CharField(max_length=200)
    updated_on = models.DateTimeField(auto_now= True)
    description = models.TextField()
    experience_required = models.IntegerField()
    picture =  models.ImageField(upload_to='jobportal/%Y/%m/%d/')
    post_picture =  models.ImageField(upload_to='jobportal/%Y/%m/%d/', blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    expired_on = models.DateTimeField()
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

jobportal/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render
from .models import Vacancy
from .choices import minexperience_choices, specialization_choices

class VacancyList(generic.ListView): 
    queryset = Vacancy.objects.filter(status=1).order_by('-created_on')
    template_name = 'jobportal/vacancy.html'

class VacancyDetail(generic.DetailView):
    model = Vacancy
    template_name = 'jobportal/vacancy_detail.html'

def searchjob(request):
  queryset_list = Vacancy.objects.order_by('-created_on')

  # Keywords
  if 'keywords' in request.GET:
    keywords = request.GET['keywords']
    if keywords:
      queryset_list = queryset_list.filter(title__icontains=keywords)

  # Area
  if 'area' in request.GET:
    area = request.GET['area']
    if area: 
      queryset_list = queryset_list.filter(area__iexact=area)

  # Experience
  if 'minexperience' in request.GET:
    minexperience = request.GET['minexperience']
    if minexperience:
      queryset_list = queryset_list.filter(experience_required__gte=minexperience)

  # Specialization
  if 'specialization' in request.GET:
    specialization = request.GET['specialization']
    if specialization:
      queryset_list = queryset_list.filter(specialization__iexact=specialization)


  context = {
      'minexperience_choices': minexperience_choices,
      'specialization_choices': specialization_choices,
      'vacancies': queryset_list,
      'values': request.GET
  }

  return render(request, 'jobportal/search.html', context)

templates/jobportal/search.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: black;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
<section id="showcase">
    <div class="container text-center">
        <div class="home-search p-5">
            <div class="overlay p-5">
                <h1 class="display-4 mb-4">
                    KonsulKarir Job Portal
                </h1>
                <div class="search">
                    <form action="{% url 'searchjob' %}">
                        <!-- Form Row 1 -->
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Keywords</label>
                                <input type="text" name="keywords" class="form-control"
                                    placeholder="Job tittle or keywords" value="{{ value.keywords }}">
                            </div>
                
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Area</label>
                                <input type="text" name="area" class="form-control"
                                placeholder="Area or City" value="{{ value.area }}">
                            </div>
                        </div>
                        <!-- Form Row 2 -->
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Minimum Experience</label>
                                <select name="minexperience" class="form-control">
                                    <option selected="true" disabled="disabled">Minimum Experience (year)</option>
                                    {% for key,value in minexperience_choices.items %}
                                        <option value="{{ key }}"
                                        {% if key == values.minexperience %}
                                            selected
                                        {% endif %}
                                        >{{ value }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="sr-only">Specialization</label>
                                <select name="specialization" class="form-control">
                                    <option selected="true" disabled="disabled">Specialization</option>
                                    {% for key,value in specialization_choices.items %}
                                    <option value="{{ key }}"
                                    {% if key == values.specialization %}
                                        selected
                                    {% endif %}
                                    >{{ value }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for vacancy in vacancies %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ vacancy.title }}</h2>
                    <p class="card-text text-muted h6"> | {{ vacancy.created_on}} </p>
                    <p class="card-text">{{vacancy.description|slice:":200" }}</p>
                    <a href="{% url 'vacancy_detail' vacancy.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{%endblock%}

templates/jobportal/vacancy.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: black;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3"> JOB PORTAL </h3>
                    <p class="">Search your opportunity here
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for vacancy in vacancy_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ vacancy.title }}</h2>
                    <p class="card-text text-muted h6">{{ vacancy.author }} | {{ vacancy.created_on}} </p>
                    <p class="card-text">{{vacancy.content|slice:":200" }}</p>
                    <a href="{% url 'vacancy_detail' vacancy.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

templates/jobportal/vacancy_detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} | {{ vacancy.title }} {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{ vacancy.title }}</h1>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'index' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'vacancy' %}">Job Portal</a>
                </li>
                <li class="breadcrumb-item active">{{ vacancy.title }}</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Alerts -->
{% include 'partials/_alerts.html' %}

<!-- Listing -->
<section id="listing" class="py-4">
    <div class="container">
        <a href="{% url 'vacancy' %}" class="btn btn-light mb-4">Back To Job Portal</a>
        <div class="row">
            <div class="col-md-8">
                <!-- Home Main Image -->
                {% if vacancy.post_picture %}
                     <img src="{{ vacancy.post_picture.url }}" alt="" class="img-main img-fluid mb-3">
                {% endif %}
                <!-- Fields -->
                <div class="row mb-5 fields">
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class=""></i> Specialization: <br>
                                <span class="">{{ vacancy.specialization }}</span>
                                
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class=""></i> Area:
                                <span class="float-right">{{ vacancy.area }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class=""></i> Experience required:
                                <span class="float-right">{{ vacancy.experience_required  }} Years</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-secondary">
                                <i class=""></i> Post Date:
                                <span class="float-right">{{ vacancy.created_on }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class=""></i> Expired Date:
                                <span class="float-right">{{ vacancy.expired_on }}</span>
                            </li>
                            <li class="list-group-item text-secondary">
                                <i class="fas fa-money-bill-alt"></i> Salary:
                                <span class="float-right">${{ vacancy.salary | intcomma }}</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-12">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <i class=""></i> Description:
                                <span class="">{{ vacancy.description }}</span>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Description -->
                <div class="row mb-5">
                    <div class="col-md-12">
                        {{ listing.description }}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4">

                    <div class="card-body">
                        <h5 class="card-title">Company:</h5>
                        <img src="{{ vacancy.picture.url }}" alt="" class="img-main img-fluid mb-3">
                        <h6 class="">{{ vacancy.company }}</h6>
                        <h6 class="">Company Size: {{ vacancy.company.company_size }} Employees</h6>
                        <h6 class="">Industry: {{ vacancy.company.industry }}</h6>
                        <h6 class="">Website: {{ vacancy.company.website }}</h6>
                        <h6 class="">Overview: {{ vacancy.company.overview }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/jobportal/vacancy_detail21.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <img src="{{ vacancy.picture.url }}" alt="" class="img-main img-fluid mb-3">
        <p class=" text-muted">{{ vacancy.author }} | {{ vacancy.created_on }}</p>
        <p class="card-text ">{{ object.description | safe }}</p>

      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 right  top">
      <div class="card-body">
        <img src="{{ vacancy.picture.url }}" alt="" class="img-main img-fluid mb-3">
        <p class=" text-muted">{{ vacancy.author }} | {{ vacancy.created_on }}</p>
        <p class="card-text ">{{ object.description | safe }}</p>

      </div>
    </div>
  </div>
</div>

{% endblock content %}